on: push
jobs:
  commit-message-check:
    runs-on: ubuntu-latest
    steps:
      - name: Post comment
        uses: KeisukeYamashita/create-comment@v1
        with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
         comment: |
            Issue title must start with 'ABC-'.
            Auto-closing this issue.
