on:
 issues:
    types:
      - labeled
jobs:
  commit-message-check:
    runs-on: ubuntu-latest
    steps:
      - name: Post comment
        uses: KeisukeYamashita/create-comment@v1
        with:
         issue-number: 1
         comment: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]
